import {
  Activity, AlertCircle, AlertTriangle, ArrowDownRight, ArrowLeft, ArrowRight, ArrowRightCircle, ArrowUpRight, Award, Ban, Banknote, BarChart, BarChart2, BarChart3, Beef, Bell, BellOff, Blocks, BrainCircuit, Building, Building2, Calendar, CalendarClock, CalendarDays, Camera, Check, CheckCircle, CheckCircle2, CheckIcon, ChefHat, ChevronDownIcon, ChevronLeft, ChevronRight, ChevronRightIcon, ChevronUpIcon, CircleCheckIcon, Clock, Cpu, CreditCard, Database, Delete, DollarSign, Download, Droplet, Edit, Edit2, ExternalLink, Eye, EyeOff, FileSpreadsheet, FileText, Filter, Fingerprint, Flame, Gift, Globe, GripVertical, Hash, HeartHandshake, HelpCircle, Image as ImageIcon, ImagePlus, Info, InfoIcon, Layers, Layout, LayoutDashboard, LayoutGrid, Leaf, LifeBuoy, ListTree, Loader2, Loader2Icon, Lock, LogIn, LogOut, Mail, MapPin, Megaphone, Menu, MenuSquare, MessageCircle, MessageSquare, MessageSquareText, Minus, MonitorCheck, MonitorSmartphone, Moon, MoreVertical, MousePointer2, OctagonXIcon, Package, PackageCheck, PackageOpen, Palette, PanelLeftIcon, PauseCircle, Percent, Phone, Play, PlayCircle, Plus, Printer, QrCode, Receipt, ReceiptText, RefreshCcw, RefreshCw, Save, ScrollText, Search, SearchIcon, Send, Server, Settings, Settings2, Shield, ShieldAlert, ShieldCheck, ShoppingBag, ShoppingCart, Sliders, Smartphone, Sparkles, Square, Star, Store, Sun, Tablet, Tag, Target, Terminal, Timer, ToggleLeft, ToggleRight, Trash, Trash2, TrendingDown, TrendingUp, TriangleAlertIcon, Truck, Type, UploadCloud, User, User as UserIcon, UserCheck, Users, Utensils, UtensilsCrossed, Wallet, Wheat, Wifi, X, XCircle, XIcon, Zap,
  type LucideIcon
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  Activity, AlertCircle, AlertTriangle, ArrowDownRight, ArrowLeft, ArrowRight, ArrowRightCircle, ArrowUpRight, Award, Ban, Banknote, BarChart, BarChart2, BarChart3, Beef, Bell, BellOff, Blocks, BrainCircuit, Building, Building2, Calendar, CalendarClock, CalendarDays, Camera, Check, CheckCircle, CheckCircle2, CheckIcon, ChefHat, ChevronDownIcon, ChevronLeft, ChevronRight, ChevronRightIcon, ChevronUpIcon, CircleCheckIcon, Clock, Cpu, CreditCard, Database, Delete, DollarSign, Download, Droplet, Edit, Edit2, ExternalLink, Eye, EyeOff, FileSpreadsheet, FileText, Filter, Fingerprint, Flame, Gift, Globe, GripVertical, Hash, HeartHandshake, HelpCircle, ImageIcon, ImagePlus, Info, InfoIcon, Layers, Layout, LayoutDashboard, LayoutGrid, Leaf, LifeBuoy, ListTree, Loader2, Loader2Icon, Lock, LogIn, LogOut, Mail, MapPin, Megaphone, Menu, MenuSquare, MessageCircle, MessageSquare, MessageSquareText, Minus, MonitorCheck, MonitorSmartphone, Moon, MoreVertical, MousePointer2, OctagonXIcon, Package, PackageCheck, PackageOpen, Palette, PanelLeftIcon, PauseCircle, Percent, Phone, Play, PlayCircle, Plus, Printer, QrCode, Receipt, ReceiptText, RefreshCcw, RefreshCw, Save, ScrollText, Search, SearchIcon, Send, Server, Settings, Settings2, Shield, ShieldAlert, ShieldCheck, ShoppingBag, ShoppingCart, Sliders, Smartphone, Sparkles, Square, Star, Store, Sun, Tablet, Tag, Target, Terminal, Timer, ToggleLeft, ToggleRight, Trash, Trash2, TrendingDown, TrendingUp, TriangleAlertIcon, Truck, Type, UploadCloud, User, UserIcon, UserCheck, Users, Utensils, UtensilsCrossed, Wallet, Wheat, Wifi, X, XCircle, XIcon, Zap
};
